export enum AdminActionsTypes {
  GET_ALL_EMPLOYEE_REQUEST = "GET_ALL_EMPLOYEE_REQUEST",
  GET_ALL_EMPLOYEE_SUCCESS = "GET_ALL_EMPLOYEE_SUCCESS",
  GET_ALL_EMPLOYEE_FAIL = "GET_ALL_EMPLOYEE_FAIL",

  GET_ALL_CLIENTS_REQUEST = "GET_ALL_CLIENTS_REQUEST",
  GET_ALL_CLIENTS_SUCCESS = "GET_ALL_CLIENTS_SUCCESS",
  GET_ALL_CLIENTS_FAIL = "GET_ALL_CLIENTS_FAIL",

  ADD_EMPLOYEE_REQUEST = "ADD_EMPLOYEE_REQUEST",
  ADD_EMPLOYEE_SUCCESS = "ADD_EMPLOYEE_SUCCESS",
  ADD_EMPLOYEE_FAIL = "ADD_EMPLOYEE_FAIL",

  ADD_CLIENT_REQUEST = "ADD_CLIENT_REQUEST",
  ADD_CLIENT_SUCCESS = "ADD_CLIENT_SUCCESS",
  ADD_CLIENT_FAIL = "ADD_CLIENT_FAIL",
}
