export enum AdminActionsTypes {
  GET_ALL_EMPLOYEE_REQUEST = "GET_ALL_EMPLOYEE_REQUEST",
  GET_ALL_EMPLOYEE_SUCCESS = "GET_ALL_EMPLOYEE_SUCCESS",
  GET_ALL_EMPLOYEE_FAIL = "GET_ALL_EMPLOYEE_FAIL",

  GET_ALL_CLIENTS_REQUEST = "GET_ALL_CLIENTS_REQUEST",
  GET_ALL_CLIENTS_SUCCESS = "GET_ALL_CLIENTS_SUCCESS",
  GET_ALL_CLIENTS_FAIL = "GET_ALL_CLIENTS_FAIL",
}
