export enum EmployeeActionsTypes {
  GET_OTP_REQUETS = "GET_OTP_REQUETS",
  GET_OTP_SUCCESS = "GET_OTP_SUCCESS",
  GET_OTP_FAIL = "GET_OTP_FAIL",

  GET_OTP_VERIFICATION_REQUETS = "GET_OTP_VERIFICATION_REQUETS",
  GET_OTP_VERIFICATION_SUCCESS = "GET_OTP_VERIFICATION_SUCCESS",
  GET_OTP_VERIFICATION_FAIL = "GET_OTP_VERIFICATION_FAIL",

  EMPLOYEE_LOGOUT_REQUETS = "EMPLOYEE_LOGOUT_REQUETS",
  EMPLOYEE_LOGOUT_SUCCESS = "EMPLOYEE_LOGOUT_SUCCESS",
  EMPLOYEE_LOGOUT_FAIL = "EMPLOYEE_LOGOUT_FAIL",

  EMPLOYEE_LOGIN_SUCCESS = "EMPLOYEE_LOGIN_SUCCESS",

  GET_MYPROFILE_REQUETS = "GET_MYPROFILE_REQUETS",
  GET_MYPROFILE_SUCCESS = "GET_MYPROFILE_SUCCESS",
  GET_MYPROFILE_FAIL = "GET_MYPROFILE_FAIL",
}
