export enum EmployeeActionsTypes {
  GET_OTP_REQUETS = "GET_OTP_REQUETS",
  GET_OTP_SUCCESS = "GET_OTP_SUCCESS",
  GET_OTP_FAIL = "GET_OTP_FAIL",

  GET_OTP_VERIFICATION_REQUETS = "GET_OTP_VERIFICATION_REQUETS",
  GET_OTP_VERIFICATION_SUCCESS = "GET_OTP_VERIFICATION_SUCCESS",
  GET_OTP_VERIFICATION_FAIL = "GET_OTP_VERIFICATION_FAIL",
}
