export enum JobActionsTypes {
  CREATE_JOB_REQUEST = "CREATE_JOB_REQUEST",
  CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS",
  CREATE_JOB_FAIL = "CREATE_JOB_FAIL",

  GET_ALL_JOBS_REQUEST = "GET_ALL_JOBS_REQUEST",
  GET_ALL_JOBS_SUCCESS = "GET_ALL_JOBS_SUCCESS",
  GET_ALL_JOBS_FAIL = "GET_ALL_JOBS_FAIL",

  GET_SINGLE_JOB_REQUEST = "GET_SINGLE_JOB_REQUEST",
  GET_SINGLE_JOB_SUCCESS = "GET_SINGLE_JOB_SUCCESS",
  GET_SINGLE_JOB_FAIL = "GET_SINGLE_JOB_FAIL",

  EDIT_JOB_REQUEST = "EDIT_JOB_REQUEST",
  EDIT_JOB_SUCCESS = "EDIT_JOB_SUCCESS",
  EDIT_JOB_FAIL = "EDIT_JOB_FAIL",
}
