export enum JobActionsTypes {
  CREATE_JOB_REQUEST = "CREATE_JOB_REQUEST",
  CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS",
  CREATE_JOB_FAIL = "CREATE_JOB_FAIL",

  GET_ALL_JOBS_REQUEST = "GET_ALL_JOBS_REQUEST",
  GET_ALL_JOBS_SUCCESS = "GET_ALL_JOBS_SUCCESS",
  GET_ALL_JOBS_FAIL = "GET_ALL_JOBS_FAIL",

  GET_SINGLE_JOB_REQUEST = "GET_SINGLE_JOB_REQUEST",
  GET_SINGLE_JOB_SUCCESS = "GET_SINGLE_JOB_SUCCESS",
  GET_SINGLE_JOB_FAIL = "GET_SINGLE_JOB_FAIL",

  EDIT_JOB_REQUEST = "EDIT_JOB_REQUEST",
  EDIT_JOB_SUCCESS = "EDIT_JOB_SUCCESS",
  EDIT_JOB_FAIL = "EDIT_JOB_FAIL",

  APPLY_JOB_REQUEST = "APPLY_JOB_REQUEST",
  APPLY_JOB_SUCCESS = "APPLY_JOB_SUCCESS",
  APPLY_JOB_FAIL = "APPLY_JOB_FAIL",

  ALL_APPLICATION_REQUEST = "ALL_APPLICATION_REQUEST",
  ALL_APPLICATION_SUCCESS = "ALL_APPLICATION_SUCCESS",
  ALL_APPLICATION_FAIL = "ALL_APPLICATION_FAIL",

  GET_SINGLE_APPLICATION_REQUEST = "GET_SINGLE_APPLICATION_REQUEST",
  GET_SINGLE_APPLICATION_SUCCESS = "GET_SINGLE_APPLICATION_SUCCESS",
  GET_SINGLE_APPLICATION_FAIL = "GET_SINGLE_APPLICATION_FAIL",

  CHANGE_APPLICATION_STATUS_REQUEST = "ALL_APPLICATION_REQUEST",
  CHANGE_APPLICATION_STATUS_SUCCESS = "CHANGE_APPLICATION_STATUS_SUCCESS",
  CHANGE_APPLICATION_STATUS_FAIL = "CHANGE_APPLICATION_STATUS_FAIL",
}
