export enum JobActionsTypes {
  CREATE_JOB_REQUEST = "CREATE_JOB_REQUEST",
  CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS",
  CREATE_JOB_FAIL = "CREATE_JOB_FAIL",

  GET_ALL_JOBS_REQUEST = "GET_ALL_JOBS_REQUEST",
  GET_ALL_JOBS_SUCCESS = "GET_ALL_JOBS_SUCCESS",
  GET_ALL_JOBS_FAIL = "GET_ALL_JOBS_FAIL",
}
