export enum LeaveActionTypes {
  GET_LEAVE_REQUEST_REQUEST = "GET_LEAVE_REQUEST_REQUEST",
  GET_LEAVE_REQUEST_SUCCESS = "GET_LEAVE_REQUEST_SUCCESS",
  GET_LEAVE_REQUEST_FAIL = "GET_LEAVE_REQUEST_FAIL",

  GET_MY_LEAVES_REQUEST = "GET_MY_LEAVES_REQUEST",
  GET_MY_LEAVES_SUCCESS = "GET_MY_LEAVES_SUCCESS",
  GET_MY_LEAVES_FAIL = "GET_MY_LEAVES_FAIL",

  APPROVE_LEAVE_REQUEST = "APPROVE_LEAVE_REQUEST",
  APPROVE_LEAVE_SUCCESS = "APPROVE_LEAVE_SUCCESS",
  APPROVE_LEAVE_FAIL = "APPROVE_LEAVE_FAIL",

  VIEW_SINGLE_LEAVE_REQUEST = "VIEW_SINGLE_LEAVE_REQUEST",
  VIEW_SINGLE_LEAVE_SUCCESS = "VIEW_SINGLE_LEAVE_SUCCESS",
  VIEW_SINGLE_LEAVE_FAIL = "VIEW_SINGLE_LEAVE_FAIL",
  
  APPLY_LEAVE_REQUEST = "APPLY_LEAVE_REQUEST",
  APPLY_LEAVE_SUCCESS = "APPLY_LEAVE_SUCCESS",
  APPLY_LEAVE_FAIL = "APPLY_LEAVE_FAIL",
}
