export enum LeaveActionTypes {
  GET_LEAVE_REQUEST_REQUEST = "GET_LEAVE_REQUEST_REQUEST",
  GET_LEAVE_REQUEST_SUCCESS = "GET_LEAVE_REQUEST_SUCCESS",
  GET_LEAVE_REQUEST_FAIL = "GET_LEAVE_REQUEST_FAIL",
}
