export enum ProfileActionsTypes {
  GET_EMPLOYEE_PROFILE_REQUETS = "GET_EMPLOYEE_PROFILE_REQUETS",
  GET_EMPLOYEE_PROFILE_SUCCESS = "GET_EMPLOYEE_PROFILE_SUCCESS",
  GET_EMPLOYEE_PROFILE_FAIL = "GET_EMPLOYEE_PROFILE_FAIL",

  GET_CLIENT_PROFILE_REQUETS = "GET_CLIENT_PROFILE_REQUETS",
  GET_CLIENT_PROFILE_SUCCESS = "GET_CLIENT_PROFILE_SUCCESS",
  GET_CLIENT_PROFILE_FAIL = "GET_CLIENT_PROFILE_FAIL",
}
