export enum ProfileActionsTypes {
  GET_EMPLOYEE_PROFILE_REQUETS = "GET_EMPLOYEE_PROFILE_REQUETS",
  GET_EMPLOYEE_PROFILE_SUCCESS = "GET_EMPLOYEE_PROFILE_SUCCESS",
  GET_EMPLOYEE_PROFILE_FAIL = "GET_EMPLOYEE_PROFILE_FAIL",

  GET_CLIENT_PROFILE_REQUETS = "GET_CLIENT_PROFILE_REQUETS",
  GET_CLIENT_PROFILE_SUCCESS = "GET_CLIENT_PROFILE_SUCCESS",
  GET_CLIENT_PROFILE_FAIL = "GET_CLIENT_PROFILE_FAIL",

  EDIT_EMPLOYEE_PROFILE_REQUETS = "EDIT_EMPLOYEE_PROFILE_REQUETS",
  EDIT_EMPLOYEE_PROFILE_SUCCESS = "EDIT_EMPLOYEE_PROFILE_SUCCESS",
  EDIT_EMPLOYEE_PROFILE_FAIL = "EDIT_EMPLOYEE_PROFILE_FAIL",

  EDIT_CLIENT_PROFILE_REQUETS = "EDIT_CLIENT_PROFILE_REQUETS",
  EDIT_CLIENT_PROFILE_SUCCESS = "EDIT_CLIENT_PROFILE_SUCCESS",
  EDIT_CLIENT_PROFILE_FAIL = "EDIT_CLIENT_PROFILE_FAIL",

  REMOVE_EMPLOYEE_PROFILE_REQUETS = "REMOVE_EMPLOYEE_PROFILE_REQUETS",
  REMOVE_EMPLOYEE_PROFILE_SUCCESS = "REMOVE_EMPLOYEE_PROFILE_SUCCESS",
  REMOVE_EMPLOYEE_PROFILE_FAIL = "REMOVE_EMPLOYEE_PROFILE_FAIL",

  CHANGE_EMPLOYEE_PASSWORD_REQUEST = " CHANGE_EMPLOYEE_PASSWORD_REQUEST",
  CHANGE_EMPLOYEE_PASSWORD_SUCCESS = " CHANGE_EMPLOYEE_PASSWORD_SUCCESS",
  CHANGE_EMPLOYEE_PASSWORD_FAIL = " CHANGE_EMPLOYEE_PASSWORD_FAIL",

  EDIT_SALARY_DETAILS_REQUETS = "EDIT_SALARY_DETAILS_REQUETS",
  EDIT_SALARY_DETAILS_SUCCESS = "EDIT_SALARY_DETAILS_SUCCESS",
  EDIT_SALARY_DETAILS_FAIL = "EDIT_SALARY_DETAILS_FAIL",


}
