export enum ProjectActionsTypes {
  GET_ALL_PROJECTS_REQUEST = "GET_ALL_PROJECTS_REQUEST",
  GET_ALL_PROJECTS_SUCCESS = "GET_ALL_PROJECTS_SUCCESS",
  GET_ALL_PROJECTS_FAIL = "GET_ALL_PROJECTS_FAIL",

  GET_SINGLE_PROJECTS_REQUEST = "GET_SINGLE_PROJECTS_REQUEST",
  GET_SINGLE_PROJECTS_SUCCESS = "GET_SINGLE_PROJECTS_SUCCESS",
  GET_SINGLE_PROJECTS_FAIL = "GET_SINGLE_PROJECTS_FAIL",

  CREATE_PROJECTS_REQUEST = "CREATE_PROJECTS_REQUEST",
  CREATE_PROJECTS_SUCCESS = "CREATE_PROJECTS_SUCCESS",
  CREATE_PROJECTS_FAIL = "CREATE_PROJECTS_FAIL",

  COMPLETE_PROJECTS_REQUEST = "COMPLETE_PROJECTS_REQUEST",
  COMPLETE_PROJECTS_SUCCESS = "COMPLETE_PROJECTS_SUCCESS",
  COMPLETE_PROJECTS_FAIL = "COMPLETE_PROJECTS_FAIL",

  EDIT_PROJECTS_REQUEST = "EDIT_PROJECTS_REQUEST",
  EDIT_PROJECTS_SUCCESS = "EDIT_PROJECTS_SUCCESS",
  EDIT_PROJECTS_FAIL = "EDIT_PROJECTS_FAIL",

  ADD_TEAM_TO_PROJECTS_REQUEST = "ADD_TEAM_TO_PROJECTS_REQUEST",
  ADD_TEAM_TO_PROJECTS_SUCCESS = "ADD_TEAM_TO_PROJECTS_SUCCESS",
  ADD_TEAM_TO_PROJECTS_FAIL = "ADD_TEAM_TO_PROJECTS_FAIL",

  REMOVE_TEAM_FROM_PROJECTS_REQUEST = "REMOVE_TEAM_FROM_PROJECTS_REQUEST",
  REMOVE_TEAM_FROM_PROJECTS_SUCCESS = "REMOVE_TEAM_FROM_PROJECTS_SUCCESS",
  REMOVE_TEAM_FROM_PROJECTS_FAIL = "REMOVE_TEAM_FROM_PROJECTS_FAIL",

  GET_MY_PROJECTS_REQUEST = "GET_MY_PROJECTS_REQUEST",
  GET_MY_PROJECTS_SUCCESS = "GET_MY_PROJECTS_SUCCESS",
  GET_MY_PROJECTS_FAIL = "GET_MY_PROJECTS_FAIL",

  GET_TASKS_UNDER_PROJECTS_REQUEST = "GET_TASKS_UNDER_PROJECTS_REQUEST",
  GET_TASKS_UNDER_PROJECTS_SUCCESS = "GET_TASKS_UNDER_PROJECTS_SUCCESS",
  GET_TASKS_UNDER_PROJECTS_FAIL = "GET_TASKS_UNDER_PROJECTS_FAIL",
}
