export enum ProjectActionsTypes {
  GET_ALL_PROJECTS_REQUEST = "GET_ALL_PROJECTS_REQUEST",
  GET_ALL_PROJECTS_SUCCESS = "GET_ALL_PROJECTS_SUCCESS",
  GET_ALL_PROJECTS_FAIL = "GET_ALL_PROJECTS_FAIL",


  CREATE_PROJECTS_REQUEST = "CREATE_PROJECTS_REQUEST",
  CREATE_PROJECTS_SUCCESS = "CREATE_PROJECTS_SUCCESS",
  CREATE_PROJECTS_FAIL = "CREATE_PROJECTS_FAIL",
}
