export enum ResourceActionTypes {
  CREATE_ASSET_REQUEST = "CREATE_ASSET_REQUEST",
  CREATE_ASSET_SUCCESS = "CREATE_ASSET_SUCCESS",
  CREATE_ASSET_FAIL = "CREATE_ASSET_FAIL",

  EDIT_ASSET_REQUEST = "EDIT_ASSET_REQUEST",
  EDIT_ASSET_SUCCESS = "EDIT_ASSET_SUCCESS",
  EDIT_ASSET_FAIL = "EDIT_ASSET_FAIL",

  DELETE_ASSET_REQUEST = "DELETE_ASSET_REQUEST",
  DELETE_ASSET_SUCCESS = "DELETE_ASSET_SUCCESS",
  DELETE_ASSET_FAIL = "DELETE_ASSET_FAIL",

  GET_ALL_ASSETS_REQUEST = "GET_ALL_ASSETS_REQUEST",
  GET_ALL_ASSETS_SUCCESS = "GET_ALL_ASSETS_SUCCESS",
  GET_ALL_ASSETS_FAIL = "GET_ALL_ASSETS_FAIL",

  GET_SINGLE_ASSET_REQUEST = "GET_SINGLE_ASSET_REQUEST",
  GET_SINGLE_ASSET_SUCCESS = "GET_SINGLE_ASSET_SUCCESS",
  GET_SINGLE_ASSET_FAIL = "GET_SINGLE_ASSET_FAIL",
}
