export enum ResourceActionTypes {
  CREATE_ASSET_REQUEST = "CREATE_ASSET_REQUEST",
  CREATE_ASSET_SUCCESS = "CREATE_ASSET_SUCCESS",
  CREATE_ASSET_FAIL = "CREATE_ASSET_FAIL",

  EDIT_ASSET_REQUEST = "EDIT_ASSET_REQUEST",
  EDIT_ASSET_SUCCESS = "EDIT_ASSET_SUCCESS",
  EDIT_ASSET_FAIL = "EDIT_ASSET_FAIL",

  DELETE_ASSET_REQUEST = "DELETE_ASSET_REQUEST",
  DELETE_ASSET_SUCCESS = "DELETE_ASSET_SUCCESS",
  DELETE_ASSET_FAIL = "DELETE_ASSET_FAIL",

  GET_ALL_ASSETS_REQUEST = "GET_ALL_ASSETS_REQUEST",
  GET_ALL_ASSETS_SUCCESS = "GET_ALL_ASSETS_SUCCESS",
  GET_ALL_ASSETS_FAIL = "GET_ALL_ASSETS_FAIL",

  GET_SINGLE_ASSET_REQUEST = "GET_SINGLE_ASSET_REQUEST",
  GET_SINGLE_ASSET_SUCCESS = "GET_SINGLE_ASSET_SUCCESS",
  GET_SINGLE_ASSET_FAIL = "GET_SINGLE_ASSET_FAIL",

  CREATE_EXPENSE_REQUEST = "CREATE_EXPENSE_REQUEST",
  CREATE_EXPENSE_SUCCESS = "CREATE_EXPENSE_SUCCESS",
  CREATE_EXPENSE_FAIL = "CREATE_ASSET_FAIL",

  EDIT_EXPENSE_REQUEST = "EDIT_EXPENSE_REQUEST",
  EDIT_EXPENSE_SUCCESS = "EDIT_EXPENSE_SUCCESS",
  EDIT_EXPENSE_FAIL = "EDIT_EXPENSE_FAIL",

  DELETE_EXPENSE_REQUEST = "DELETE_EXPENSE_REQUEST",
  DELETE_EXPENSE_SUCCESS = "DELETE_EXPENSE_SUCCESS",
  DELETE_EXPENSE_FAIL = "DELETE_EXPENSE_FAIL",

  GET_ALL_EXPENSES_REQUEST = "GET_ALL_EXPENSES_REQUEST",
  GET_ALL_EXPENSES_SUCCESS = "GET_ALL_EXPENSES_SUCCESS",
  GET_ALL_EXPENSES_FAIL = "GET_ALL_EXPENSES_FAIL",

  GET_SINGLE_EXPENSE_REQUEST = "GET_SINGLE_EXPENSE_REQUEST",
  GET_SINGLE_EXPENSE_SUCCESS = "GET_SINGLE_EXPENSE_SUCCESS",
  GET_SINGLE_EXPENSE_FAIL = "GET_SINGLE_EXPENSE_FAIL",

  REQUEST_PAYOUT_REQUEST = "REQUEST_PAYOUT_REQUEST",
  REQUEST_PAYOUT_SUCCESS = "REQUEST_PAYOUT_SUCCESS",
  REQUEST_PAYOUT_FAIL = "REQUEST_PAYOUT_FAIL",

  COMPLETE_PAYOUT_REQUEST = "COMPLETE_PAYOUT_REQUEST",
  COMPLETE_PAYOUT_SUCCESS = "COMPLETE_PAYOUT_SUCCESS",
  COMPLETE_PAYOUT_FAIL = "COMPLETE_PAYOUT_FAIL",

  GET_ALL_PAYOUTS_REQUEST = "GET_ALL_PAYOUTS_REQUEST",
  GET_ALL_PAYOUTS_SUCCESS = "GET_ALL_PAYOUTS_SUCCESS",
  GET_ALL_PAYOUTS_FAIL = "GET_ALL_PAYOUTS_FAIL",
}
