export enum TenantActionsTypes {
  AUTH_REQUETS = "AUTH_REQUETS",
  AUTH_SUCCESS = "AUTH_SUCCESS",
  AUTH_FAIL = "AUTH_FAIL",
  LOGOUT_SUCCESS = "LOGOUT_SUCCESS",

  GET_OTP_REQUEST = "GET_OTP_REQUEST",
  GET_OTP_SUCCESS = "GET_OTP_SUCCESS",
  GET_OTP_FAIL = "GET_OTP_FAIL",

  GET_PAID_TENANT_SUCCESS = "GET_PAID_TENANT_SUCCESS",
  GET_PAID_TENANT_FAIL = "GET_PAID_TENANT_FAIL",

  SENT_STRIPE_LINK_SUCCESS = "SENT_STRIPE_LINK_SUCCESS",
  SENT_STRIPE_LINK_FAIL = "SENT_STRIPE_LINK_FAIL",

  RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST",
  RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL",
}
