export enum TenantActionsTypes {
  AUTH_REQUETS = "AUTH_REQUETS",
  AUTH_SUCCESS = "AUTH_SUCCESS",
  AUTH_FAIL = "AUTH_FAIL",
  LOGOUT_SUCCESS = "LOGOUT_SUCCESS",

  GET_OTP_REQUEST = "GET_OTP_REQUEST",
  GET_OTP_SUCCESS = "GET_OTP_SUCCESS",
  GET_OTP_FAIL = "GET_OTP_FAIL",

}
