export enum TenantActionsTypes {
  AUTH_REQUETS = "BUY_PRODUCT_REQUETS",
  AUTH_SUCCESS = "BUY_PRODUCT_SUCCESS",
  AUTH_FAIL = "BUY_PRODUCT_FAIL",

  GET_OTP_REQUEST = "GET_OTP_REQUEST",
  GET_OTP_SUCCESS = "GET_OTP_SUCCESS",
  GET_OTP_FAIL = "GET_OTP_FAIL",
}
